#!/usr/bin/env python3
"""Add this app to the pinned Cobalt checkout's USB device package.

The prepared package keeps Cobalt as the hardware/runtime layer but makes
E-Ink Chess the owner-facing application:

    NickelMenu -> E-Ink Chess -> kobod -> Kobo hardware

The stock Cobalt launcher remains in the package for Cobalt itself, but the
NickelMenu entry generated by this prepared checkout launches Chess directly.
"""

from pathlib import Path
import shutil
import subprocess
import sys


PINNED_COBALT = "026ac5561add0157109dd98592272ce9c6eb9343"
APP = Path(__file__).resolve().parents[1]
COBALT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else APP.parent / "Cobalt"


def add_after(path: Path, anchor: str, addition: str) -> None:
    text = path.read_text()
    if addition in text:
        return
    if text.count(anchor) != 1:
        raise SystemExit(f"Cannot find one insertion point in {path}")
    path.write_text(text.replace(anchor, anchor + addition, 1))


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    if new in text:
        return
    if text.count(old) != 1:
        raise SystemExit(f"Cannot find one replacement point in {path}")
    path.write_text(text.replace(old, new, 1))


def insert_before(path: Path, anchor: str, addition: str) -> None:
    text = path.read_text()
    if addition in text:
        return
    if text.count(anchor) != 1:
        raise SystemExit(f"Cannot find one insertion point in {path}")
    path.write_text(text.replace(anchor, addition + anchor, 1))


if not (COBALT / "Cargo.toml").is_file():
    raise SystemExit(f"Cobalt checkout not found at {COBALT}")
revision = subprocess.check_output(
    ["git", "-C", str(COBALT), "rev-parse", "HEAD"], text=True
).strip()
if revision != PINNED_COBALT:
    raise SystemExit(f"Cobalt is at {revision}; this app requires {PINNED_COBALT}")

destination = COBALT / "examples" / "eink-chess"
(destination / "src").mkdir(parents=True, exist_ok=True)
for name in ("main.rs", "board.rs"):
    shutil.copy2(APP / "src" / name, destination / "src" / name)
(destination / "Cargo.toml").write_text(
    '[package]\n'
    'name = "kobo-eink-chess"\n'
    'version = "0.1.0"\n'
    'edition.workspace = true\n'
    'rust-version.workspace = true\n'
    'publish = false\n\n'
    '[dependencies]\n'
    'kobo-sdk = { path = "../../crates/kobo-sdk" }\n\n'
    '[lints]\n'
    'workspace = true\n'
)

add_after(
    COBALT / "Cargo.toml",
    '    "examples/tictactoe",\n',
    '    "examples/eink-chess",\n',
)
add_after(
    COBALT / "crates" / "kobo-cli" / "src" / "main.rs",
    '    ("kobo-tictactoe", None),\n',
    '    ("kobo-eink-chess", None),\n',
)
add_after(
    COBALT / "crates" / "kobod" / "src" / "app_store.rs",
    'const MANAGED_BUILTINS: &[BuiltinApp] = &[\n',
    '    BuiltinApp {\n'
    '        id: "eink-chess",\n'
    '        title: "E-Ink Chess",\n'
    '        label: "Chess",\n'
    '        summary: "Move pieces freely on a touch chessboard.",\n'
    '        version: "0.1.0",\n'
    '        glyph: Glyph::Grid,\n'
    '        capabilities: &[],\n'
    '    },\n',
)

# Cobalt's normal owner entry presents kobo-launcher. For this project we keep
# the same safe start script and kobod panel handoff, but make the chess binary
# the root application. Exiting the root application therefore ends the whole
# panel session and restores Nickel.
replace_once(
    COBALT / "crates" / "kobo-cli" / "src" / "main.rs",
    'exec \\"$root/bin/kobod\\" --present \\"$root/bin/kobo-launcher\\" > /mnt/onboard/kobod.txt 2>&1',
    'exec \\"$root/bin/kobod\\" --present \\"$root/bin/kobo-eink-chess\\" > /mnt/onboard/kobod.txt 2>&1',
)

# Reuse Cobalt's stable .adds/cobalt-launch.sh bootstrap, but expose this app
# directly in NickelMenu instead of exposing the intermediate Cobalt launcher.
replace_once(
    COBALT / "crates" / "kobo-cli" / "src" / "menu.rs",
    'menu_item :main :Cobalt :cmd_spawn :quiet:{}',
    'menu_item :main :E-Ink Chess :cmd_spawn :quiet:{}',
)

# Keep the board mark change in Cobalt's board layout, where the cell geometry
# is known. Other grid and tile icons retain their existing 3/5 size.
replace_once(
    COBALT / "crates" / "kobo-ui" / "src" / "lib.rs",
    '                        Some(glyph) => {\n'
    '                            let mark = min(cell_height, cell_width) * 3 / 5;\n',
    '                        Some(glyph) => {\n'
    '                            // Chess pieces use more of their square while\n'
    '                            // retaining a safe margin from the border.\n'
    '                            let mark = if chess_board {\n'
    '                                min(cell_height, cell_width) * 4 / 5\n'
    '                            } else {\n'
    '                                min(cell_height, cell_width) * 3 / 5\n'
    '                            };\n',
)

# The imported chess paths contain closed body contours and open detail
# strokes. Shape::Fill closes each contour during rasterisation, so filling
# these paths gives black pieces a solid silhouette without inventing a second
# chess drawing or using an oversized stroke. White pieces continue through
# the normal Tabler outline path. Keep this branch chess-specific: unrelated
# Cobalt glyphs retain their normal outline rendering.
replace_once(
    COBALT / "crates" / "kobo-ui" / "src" / "vector.rs",
    '    if let Some(shapes) = game_piece_shapes(glyph) {\n'
    '        return shapes;\n'
    '    }\n'
    '    let width = if matches!(\n'
    '        glyph,\n'
    '        Glyph::ChessBlackKing\n'
    '            | Glyph::ChessBlackQueen\n'
    '            | Glyph::ChessBlackRook\n'
    '            | Glyph::ChessBlackBishop\n'
    '            | Glyph::ChessBlackKnight\n'
    '            | Glyph::ChessBlackPawn\n'
    '    ) {\n'
    '        WEIGHT * 2\n'
    '    } else {\n'
    '        WEIGHT\n'
    '    };\n'
    '    tabler::outline(glyph)\n'
    '        .iter()\n'
    '        .map(|commands| Shape::Stroke {\n'
    '            path: Path::from_commands(commands),\n'
    '            width,\n'
    '        })\n'
    '        .collect()\n',
    '    if let Some(shapes) = game_piece_shapes(glyph) {\n'
    '        return shapes;\n'
    '    }\n'
    '    if matches!(\n'
    '        glyph,\n'
    '        Glyph::ChessBlackKing\n'
    '            | Glyph::ChessBlackQueen\n'
    '            | Glyph::ChessBlackRook\n'
    '            | Glyph::ChessBlackBishop\n'
    '            | Glyph::ChessBlackKnight\n'
    '            | Glyph::ChessBlackPawn\n'
    '    ) {\n'
    '        // The chess source has closed body contours plus open detail\n'
    '        // strokes. Fill closes each contour in the rasterizer, producing\n'
    '        // a true black silhouette without the old oversized stroke.\n'
    '        return tabler::outline(glyph)\n'
    '            .iter()\n'
    '            .map(|commands| Shape::Fill(Path::from_commands(commands)))\n'
    '            .collect();\n'
    '    }\n'
    '    tabler::outline(glyph)\n'
    '        .iter()\n'
    '        .map(|commands| Shape::Stroke {\n'
    '            path: Path::from_commands(commands),\n'
    '            width: WEIGHT,\n'
    '        })\n'
    '        .collect()\n',
)

# Add a renderer-level regression test beside Cobalt's existing chess tests.
# It checks solid interior coverage rather than relying on a screenshot.
insert_before(
    COBALT / "crates" / "kobo-ui" / "src" / "vector.rs",
    '    #[test]\n    fn chess_pieces_are_vector_art_with_distinct_sides() {',
    '    #[test]\n'
    '    fn black_chess_pieces_have_filled_interiors() {\n'
    '        for (white, black) in [\n'
    '            (Glyph::ChessWhiteKing, Glyph::ChessBlackKing),\n'
    '            (Glyph::ChessWhiteQueen, Glyph::ChessBlackQueen),\n'
    '            (Glyph::ChessWhiteRook, Glyph::ChessBlackRook),\n'
    '            (Glyph::ChessWhiteBishop, Glyph::ChessBlackBishop),\n'
    '            (Glyph::ChessWhiteKnight, Glyph::ChessBlackKnight),\n'
    '            (Glyph::ChessWhitePawn, Glyph::ChessBlackPawn),\n'
    '        ] {\n'
    '            let white_solid = render(&shapes(white), 96)\n'
    '                .alpha\n'
    '                .iter()\n'
    '                .filter(|&&value| value == 255)\n'
    '                .count();\n'
    '            let black_solid = render(&shapes(black), 96)\n'
    '                .alpha\n'
    '                .iter()\n'
    '                .filter(|&&value| value == 255)\n'
    '                .count();\n'
    '            assert!(\n'
    '                black_solid > white_solid,\n'
    '                "{black:?} has no filled interior: {black_solid} <= {white_solid}"\n'
    '            );\n'
    '        }\n'
    '    }\n\n',
)

print(f"Prepared {destination} for direct NickelMenu launch through Cobalt")
