#!/usr/bin/env python3
"""Add this app to the pinned Cobalt checkout's USB device package.

The prepared package keeps Cobalt as the hardware/runtime layer but makes
E-Ink Chess the owner-facing application:

    NickelMenu -> E-Ink Chess -> kobod -> Kobo hardware

The stock Cobalt launcher remains in the package for Cobalt itself, but the
NickelMenu entry generated by this prepared checkout launches Chess directly.
"""

from pathlib import Path
import shutil
import subprocess
import sys


PINNED_COBALT = "ecbe828da2ba163437ddd1e870079f5d41a5d2dd"
APP = Path(__file__).resolve().parents[1]
COBALT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else APP.parent / "Cobalt"


def add_after(path: Path, anchor: str, addition: str) -> None:
    text = path.read_text()
    if addition in text:
        return
    if text.count(anchor) != 1:
        raise SystemExit(f"Cannot find one insertion point in {path}")
    path.write_text(text.replace(anchor, anchor + addition, 1))


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    if new in text:
        return
    if text.count(old) != 1:
        raise SystemExit(f"Cannot find one replacement point in {path}")
    path.write_text(text.replace(old, new, 1))


def insert_before(path: Path, anchor: str, addition: str) -> None:
    text = path.read_text()
    if addition in text:
        return
    if text.count(anchor) != 1:
        raise SystemExit(f"Cannot find one insertion point in {path}")
    path.write_text(text.replace(anchor, addition + anchor, 1))


if not (COBALT / "Cargo.toml").is_file():
    raise SystemExit(f"Cobalt checkout not found at {COBALT}")
revision = subprocess.check_output(
    ["git", "-C", str(COBALT), "rev-parse", "HEAD"], text=True
).strip()
if revision != PINNED_COBALT:
    raise SystemExit(f"Cobalt is at {revision}; this app requires {PINNED_COBALT}")

destination = COBALT / "examples" / "eink-chess"
(destination / "src").mkdir(parents=True, exist_ok=True)
for name in ("main.rs", "board.rs"):
    shutil.copy2(APP / "src" / name, destination / "src" / name)
main = destination / "src" / "main.rs"
main.write_text(
    main.read_text().replace(
        'include_str!("../examples/positions.fen")',
        'include_str!("positions.fen")',
    )
)
shutil.copy2(APP / "examples" / "positions.fen", destination / "src" / "positions.fen")
(destination / "Cargo.toml").write_text(
    '[package]\n'
    'name = "kobo-eink-chess"\n'
    'version = "0.1.0"\n'
    'edition.workspace = true\n'
    'rust-version.workspace = true\n'
    'publish = false\n\n'
    '[dependencies]\n'
    'kobo-sdk = { path = "../../crates/kobo-sdk" }\n\n'
    '[lints]\n'
    'workspace = true\n'
)

add_after(
    COBALT / "Cargo.toml",
    '    "examples/tictactoe",\n',
    '    "examples/eink-chess",\n',
)
add_after(
    COBALT / "crates" / "kobo-cli" / "src" / "main.rs",
    '    ("kobo-tictactoe", None),\n',
    '    ("kobo-eink-chess", None),\n',
)
add_after(
    COBALT / "crates" / "kobod" / "src" / "app_store.rs",
    'const MANAGED_BUILTINS: &[BuiltinApp] = &[\n',
    '    BuiltinApp {\n'
    '        id: "eink-chess",\n'
    '        title: "E-Ink Chess",\n'
    '        label: "Chess",\n'
    '        summary: "Move pieces freely on a touch chessboard.",\n'
    '        version: "0.1.0",\n'
    '        glyph: Glyph::Grid,\n'
    '        capabilities: &[],\n'
    '    },\n',
)

# Cobalt's normal owner entry presents kobo-launcher. For this project we keep
# the same safe start script and kobod panel handoff, but make the chess binary
# the root application. Exiting the root application therefore ends the whole
# panel session and restores Nickel.
replace_once(
    COBALT / "crates" / "kobo-cli" / "src" / "main.rs",
    'exec \\"$root/bin/kobod\\" --present \\"$root/bin/kobo-launcher\\" > /mnt/onboard/kobod.txt 2>&1',
    'exec \\"$root/bin/kobod\\" --present \\"$root/bin/kobo-eink-chess\\" > /mnt/onboard/kobod.txt 2>&1',
)

# Reuse Cobalt's stable .adds/cobalt-launch.sh bootstrap, but expose this app
# directly in NickelMenu instead of exposing the intermediate Cobalt launcher.
replace_once(
    COBALT / "crates" / "kobo-cli" / "src" / "menu.rs",
    'menu_item :main :Cobalt :cmd_spawn :quiet:{}',
    'menu_item :main :E-Ink Chess :cmd_spawn :quiet:{}',
)

print(f"Prepared {destination} for direct NickelMenu launch through Cobalt")
